name: build and push on release and tag

on:
  push:
    tags:
      - "v*.*.*"

  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rpedde/pt750/pt750
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tag_semver: true
